import Head from 'next/head'
import Plan from '../components/Plan'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Plan />
      {/**<MainSection /> */}
      {/**<TVSection /> */}
      {/**<EverywhereSection /> */}
      {/**<ProfilesSection /> */}
      {/**<OfflineSection /> */}
      {/**<FAQSection /> */}
      {/**<Footer /> */}

    </div>
  )
}
